apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: S3 instrumenting
on:
  workflow_dispatch:
jobs:
  upload-to-s3:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Create File
        shell: sh
        run: |
          echo "hello world" > hello.txt
      - uses: cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-session-token: ${{ secrets.aws_session_token }}
      - id: workspace-to-s3-upload
        name: upload to s3
        uses: cloudbees-io/s3-upload-object@v1
        with:
          file-path: ${{ cloudbees.workspace }}/hello.txt
          bucketname: cluster.ecloud-demo.com
          s3-path: hello.txt
          action-type: upload
